Feature/independence database
RUGSoftEng/2017-Hestia-Server pull request #116
Opened 2017-05-25 11:39 UTC by szijerveld

2017-05-25 14:43 UTC, suzannemaquelin submitted a review, later dismissed
Looks good in general! Just some minor remarks

2017-05-25 14:43 UTC, suzannemaquelin commented on source/database/FileDatabase.py
> +class FileDatabase(Database):
This class should be removed

2017-05-25 14:43 UTC, suzannemaquelin commented on source/database/TinyDatabase.py
> +            message = "Inconsistent database, more then one device with the " \
What does the \ do at the at of this line?

2017-05-25 14:43 UTC, suzannemaquelin commented on source/logic/__init__.py
> +_device_database = TinyDatabase("hestia")
Eventually it would be nice to choose your database when you start the server

2017-05-25 14:43 UTC, suzannemaquelin commented on source/tests/database_tests/test_device_database_tiny_db.py
> +        self.assertNotEqual(database_data, self.empty_data)
You only test if you get a device, not if you get the right one

2017-05-28 08:24 UTC, szijerveld commented on source/tests/database_tests/test_device_database_tiny_db.py
> +        self.assertNotEqual(database_data, self.empty_data)
There is only one device in the database so that's why.

2017-05-28 08:25 UTC, szijerveld commented on source/database/TinyDatabase.py
> +            message = "Inconsistent database, more then one device with the " \
It allows to have the + on the next line.

2017-05-28 08:26 UTC, szijerveld commented on source/database/FileDatabase.py
> +class FileDatabase(Database):
Will do

2017-05-28 08:29 UTC, szijerveld commented on source/logic/__init__.py
> +_device_database = TinyDatabase("hestia")
Yeah it would. But at this moment we will not do that.

2017-05-28 10:14 UTC, LarsHoldijk requested changes

2017-05-28 10:14 UTC, LarsHoldijk commented on source/database/TinyDatabase.py
> +        pass
Is this pass still in use?

2017-05-28 10:14 UTC, LarsHoldijk commented on source/tests/database_tests/test_device_database_mongo_db.py
> +from tests import tests_util
We have had multiple switches between how we import the util methods. We should decide on a standard.

2017-05-28 10:25 UTC, LarsHoldijk approved these changes

2017-05-28 13:34 UTC, merged