Feature/automatedID
RUGSoftEng/2017-Hestia-Server pull request #24
Opened 2017-03-28 11:06 UTC by suzannemaquelin

Id of device and activators are made upon creation, device assigns id to its activators, database assigns id to new devices

2017-03-28 16:45 UTC, szijerveld requested changes
Please have a look at my comments.
I think it will not be that much work to change it and it would make it better I think.

2017-03-28 16:45 UTC, szijerveld commented on source/model/Activator.py
> +    @abstractmethod
Just a question. As all activators require an Id I think it is best that it is not an abstract  method but that activator itself implements the id. This way a lot of duplicate code is removed.
What do you think?

2017-03-28 16:45 UTC, szijerveld commented on source/model/Device.py
> +    @property
The same as with Activator.
It would be neither if the device implements the id him self.

2017-03-29 06:57 UTC, suzannemaquelin commented on source/model/Activator.py
> +    @abstractmethod
I agree. Changed it now

2017-03-29 08:00 UTC, szijerveld approved these changes

2017-03-29 08:00 UTC, merged