Rewrite in pip8 convention.
RUGSoftEng/2017-Hestia-Server pull request #29
Opened 2017-03-29 15:24 UTC by szijerveld

Fixes #20.
A rewrite to pip8 style convention to make the code more consistent.

2017-03-29 15:45 UTC, suzannemaquelin requested changes
Most of it looks fine, had two questions about it

2017-03-29 15:45 UTC, suzannemaquelin commented on source/endpoints/devices/Activator.py
>      , "requiredInfo": ToString(attribgute="requiredInfo", required=True, discription="The info needed to operate")
I think its best to stick with single quotes here as well

2017-03-29 15:45 UTC, suzannemaquelin commented on source/plugins/hestia/dimmableLight/ActivateLight.py
> +        if self.state is True:
I'm not sure if you can do this in python but shouldn't you leave out the "is True"?

2017-03-30 06:50 UTC, szijerveld commented on source/plugins/hestia/dimmableLight/ActivateLight.py
> +        if self.state is True:
I, think it is clearer if it states if this is true, instead of is this. But that is just my opinion.

2017-03-30 06:50 UTC, szijerveld commented on source/endpoints/devices/Activator.py
>      , "requiredInfo": ToString(attribgute="requiredInfo", required=True, discription="The info needed to operate")
Good one I will change this.

2017-03-30 07:20 UTC, suzannemaquelin commented on source/plugins/hestia/dimmableLight/ActivateLight.py
> +        if self.state is True:
PIP 8 says:
Don't compare boolean values to True or False using == .

Yes:   if greeting:
No:    if greeting == True:
Worse: if greeting is True:

2017-03-30 07:45 UTC, szijerveld commented on source/plugins/hestia/dimmableLight/ActivateLight.py
> +        if self.state is True:
O nice Work. 
Probably I am the worst person out there then :stuck_out_tongue_winking_eye: 
Will change it right away.

2017-03-30 07:47 UTC, suzannemaquelin approved these changes

2017-03-30 07:47 UTC, merged